services:
  app:
    build: .
    image: my-image-sd:latest
    deploy:
      replicas: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app