events { worker_connections 1024; }
http {
    upstream backend_java {
        server app:1234;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_java;
        }
    }
}